[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replaced STM32F429ZITx with STM32F401CCUx as listed in `probe-rs chip list`
runner = "probe-rs run --chip STM32F401CCUx"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
