apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`orion.nest.jurabytes.net`)
    kind: Rule
    services:
    - name: plex-media-server
      port: pms
  tls:
    certResolver: letsencrypt
