[warm-1/rips]
recursive=true
autoprune=true
autosnap=true

hourly=30
daily=10
weekly=4
monthly=0
yearly=0

[warm-1/vault]
recursive=true
autoprune=true
autosnap=true

hourly=30
daily=10
weekly=4
monthly=0
yearly=0
