apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app.kubernetes.io/name: gitea
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gitea
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 950
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 950
        runAsNonRoot: true
        runAsUser: 3000
      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.27.2-rootless
          imagePullPolicy: Always
          securityContext:
            runAsGroup: 950
            runAsNonRoot: true
            runAsUser: 3000
            capabilities:
              drop: [ALL]
          env:
            - name: GITEA__server__ROOT_URL
              value: "https://{{ .Values.host }}:443"
            - name: GITEA__server__HTTP_PORT
              value: "3000"
            - name: GITEA__server__SSH_PORT
              value: "22"
            - name: GITEA__server__SSH_LISTEN_PORT
              value: "2222"
            - name: GITEA__service__DISABLE_REGISTRATION
              value: "true"
          ports:
            - protocol: TCP
              name: http
              containerPort: 3000
            - protocol: TCP
              name: ssh
              containerPort: 2222
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 200
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          volumeMounts:
            - mountPath: /var/lib/gitea
              name: data
            - mountPath: /etc/gitea
              name: config
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: config
          hostPath:
            path: /hot-1/vault/cowtea/config
            type: Directory
        - name: data
          hostPath:
            path: /hot-1/vault/cowtea/data
            type: Directory
        - name: tmp
          emptyDir:
            medium: Memory
