apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: gitea
spec:
  storageClassName: zfs-local-hot-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/component: gitea
spec:
  storageClassName: zfs-local-hot-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
