apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app.kubernetes.io/name: gitea
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: http
    - port: 22
      protocol: TCP
      name: ssh
      targetPort: ssh
  selector:
    app.kubernetes.io/name: gitea
