apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &name frigate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/juravenator/xserve-nas.git"
    targetRevision: stable
    path: argocd/frigate
    helm:
      releaseName: *name
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *name
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
